language: go

go:
  - 1.14.x

env:
  - GO111MODULE=on

script:
  - make travis
  - ls -l bin

deploy:
  provider: releases
  api_key:
    secure: SKyXzIRIUCQ769fKVqpfKVSptKTBMgdX4j34W9wpIQ8/u11L85EQr2fl59Ziai1nLuKC6RFHG2MS/uBJkZWMA1mVP6JNxZ28BZuoWd3PwBMZc2TUrDuRwYEU+h8b1Hxlq5kpOdI3A9TnRZgJHBISD07yW2K340nr2ihmILzGEIMW0nr5fytW/+bG2gLTiS0tGvhq44BgQu2Db8wE0LChYaq46s1PZxO2cU8o+44W/cu5P2Oz0VMQQYZtTy3t5UtcidsIKUFOAybvfRXwVsk9oZNniQM5J7mH08QLYBmwNKpTJkpdcbzyFp40q+QMLtuBf6z+bainQIBb3CBSDJmJJEwFyRNNUfob3KRwiCxYwpOTbTxIh9L+YY8FxjciK70AEQ+RvPMQFR0HZkCn2AhTiDG+4PqI2BKrxx3nvxzIY+02/i5LslVwGSKUi5Y+D+7nGkMLeNXbV0m7VFdmcRyZN6ClL6zsyOhbpgzzPst1LZVKMBPmN+pZ4LbofW4p0X39Ezy+UypYGrcwkuZdNXfm8UQq+hi6LrGZwM4Q7cLPY524UVyXPPchJtKB0TjDnVeMgVToUe6JV65XdrKKgzmJoXqZn2H520HIDd0LTHqZ4z2wY/B4dynQwtSmnuvfz/bJhA+TBiY11uWhWnB36E5xxOooijQqYWFN/YtVhTZe3bs=
  file: bin/server-${TRAVIS_TAG}.tar.gz
  on:
    repo: VEuPathDB/util-user-dataset-handler-server
    tags: true
  skip_cleanup: 'true'
