# Injectable Variables:
#   <<date>>
#     The execution UTC date formatted as "2020-05-01"
#
#   <<time>>
#     the execution UTC time as "16:17:34"
#
#   <<timestamp>>
#     the execution UTC timestamp as seconds from the Unix Epoch
#
#   <<date-time>>
#     the execution UTC date & time as "2020-05-01T16:37:34Z"
#
#   <<input-files>>
#     A space separated list of all the files in a payload, sorted by name
#     ascending.
#
#     This variable allows array style access using square brackets `[]` from
#     a zero index.  For example `<<input-files[0]>>` would cause the first file
#     in the list to be injected.
#
#   <<cwd>>
#     The working directory containing all of the input files.
#
#   <<user-id>>
#     The WDK user ID of the user that initiated the request.
#
#   <<project>>
#     the name of the project this request originated from

# Example Configuration
commands:
  - command: fizz-command
    args: [
      "--time=<<time>>",
      "-u", "<<user-d>>",
      '--files="<<input-files>>"'
    ]
