# Config Template
#
# Please edit the variables below and rename this file.

service-name: my service
command:
  executable: /app/EuPathGalaxy/Tools/bin/exportBiomToEuPathDB
  args:
    # dataset name
    - <<ds-name>>
    # dataset summary
    - <<ds-summary>>
    # dataset description
    - <<ds-description>>
    # dataset uploader "email" (for auth purposes, not a real email address)
    # <wdk user name>.<wdk user id>@veupathdb.org
    - <<ds-user-email>>
    # path to XML lib
    - /app/EuPathGalaxy/Tools/lib/xml
    # output file (ignored)
    - html.html
    # ???
    - ""
    # dataset file path
    - <<input-files[0]>>