= Exporter Script Server
// General Doc Settings
:toc: left
:source-highlighter: pygments
:icons: font
// Custom vars
:repo-url: https://github.com/VEuPathDB/util-exporter-server
:repo-file-base: {repo-url}/blob/master
:file-config-readme: {repo-file-base}/extras/readme/config.adoc
// Github specifics
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:file-config-readme: {repo-file-base}/extras/readme/config.adoc
endif::[]
Elizabeth Paige Harper <epharper@upenn.edu>
v1.0.0

Exposes configured exporter / validation scripts over HTTP.

== Usage

=== In Script Container

==== Standard Use

WARNING: TODO: Create demo script container repo and provide link here

==== Custom Use

To create a custom setup not based on the demo container, this server can be
configured by performing the following steps.

CAUTION: Currently, this server app only supports linux & mac environments.

. Download the latest release from the {repo-url}/releases/latest[releases page]
  and unpack the archive in your project directory.
. Run the command `./service gen-config` to generate a server configuration
  template file.  This file will be named `config.tpl.yml`.
. Edit the configuration file with your desired service name and command
  configurations.
+
NOTE: Check the {file-config-readme}[config file readme] for more
information about the configuration file.
. Once you have edited the configuration file, rename it and place it in the
  desired relative to the service binary.
. Validate the configuration by running the command
  `./service check-config --config=path/to/your/config.yml`.  This command will
  validate the configuration and report any errors.
+
.Bad Config Example
[source, bash-session]
----
$ ./service --config=config.yml check-config

----
