= Exporter Script Server
// General Doc Settings
:toc: left
:source-highlighter: pygments
:icons: font
// Github specifics
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
Elizabeth Paige Harper <epharper@upenn.edu>
v1.0.0

// Custom Config
:repo-url: https://github.com/VEuPathDB/util-user-dataset-handler-server
:site-url: https://veupathdb.github.io/util-user-dataset-handler-server
:repo-file-base: {repo-url}/blob/master

image:https://www.travis-ci.org/VEuPathDB/util-user-dataset-handler-server.svg?branch=master["Build Status", link="https://www.travis-ci.org/VEuPathDB/util-user-dataset-handler-server"]
image:https://goreportcard.com/badge/github.com/VEuPathDB/util-user-dataset-handler-server["Go Report Card", link="https://goreportcard.com/report/github.com/VEuPathDB/util-user-dataset-handler-server"]
image:https://img.shields.io/github/v/release/VEuPathDB/util-user-dataset-handler-server["Latest Release", link="https://github.com/VEuPathDB/util-user-dataset-handler-server/releases/latest"]


Exposes configured exporter / validation scripts over HTTP.

ifdef::env-github[]
{site-url}[Rendered Readme] | 
endif::[]
{site-url}/api.html[API Docs]

== Usage

=== In Script Container

==== Standard Use

https://github.com/VEuPathDB/dataset-handlers/tree/master/biom[Sample project using this server]


==== Custom Use

To create a custom setup not based on the demo container, this server can be
configured by performing the following steps.

CAUTION: Currently, this server app only supports linux & mac environments.

. Download the latest release from the {repo-url}/releases/latest[releases page]
  and unpack the archive in your project directory.
. Run the command `./service gen-config` to generate a server configuration
  template file.  This file will be named `config.tpl.yml`.
. Edit the configuration file with your desired service name and command
  configurations.
+
NOTE: Check the {file-config-readme}[config file readme] for more
information about the configuration file.
. Once you have edited the configuration file, rename it and place it in the
  desired relative to the service binary.
. Validate the configuration by running the command
  `./service check-config --config=path/to/your/config.yml`.  This command will
  validate the configuration and report any errors.
+
.Bad Config Example
[source, bash-session]
----
$ ./service --config=config.yml check-config
----

== Config File

=== Components

.config.yml
[source, yaml]
----
service-name: my service <1>
command:
  executable: /some/path/to/your/executable <2>
  args: <3>
    - <<input-files>> <4>
----
<1> The display name of the running service
<2> Path to an executable script or binary to be called by the server to process
    uploaded datasets.
<3> An array of arguments that will be passed to the configured executable.
    Each array element is effectively a single, quote wrapped cli arg.
+
WARNING: Space separated entries in the args array _will_ be treated as a single
         argument.
<4> An <<Variables,Injected Variable>>

=== Command Context

The configured command will be executed in an isolated subshell, but will be
provided the same environment as the server itself, meaning it is possible to
set environment variables for the script simply by setting them on the docker
container.

The output of the script's `stdout` will be piped through the server's logging
mechanism and will appear in the container logs.

The output of the script's `stderr` will be both piped through the server's
logging mechanism (like `stdout`) but will also be captured for parsing and
returning to the caller.

=== Variables

==== `+<<cwd>>+`

The working directory for the job that is running in the current request.

.Example
----
/workspace/12345
----

==== `+<<date>>+`

The current date formatted as `YYYY-MM-DD`.

.Example
----
1994-02-13
----

==== `+<<date-time>>+`

The current datetime in RFC3339 format.

.Example
----
2018-10-31T23:37:18.013557+0500
----

==== `+<<ds-description>>+`

The user provided description for the current dataset upload.

.Example
----
My dataset upload containing foo and bar
----

==== `+<<ds-name>>+`

The user provided name for the current dataset upload.

.Example
----
My Dataset 3
----

==== `+<<ds-summary>>+`

The user provided summary of the current dataset upload.

.Example
----
Some summary text for my dataset upload
----

==== `+<<ds-user-email>>+`

A generated "email address" consumed by the exporter script.  This is a
generated string in the form of an email address containing the WDK user id of
the requesting user.  This is only formatted as an email address for exporter
compatibility reasons.

.Example
----
handler.123456@veupathdb.org
----

==== `+<<input-files>>+`

A space separated list of the files that were unpacked from the uploaded zip or
tar file sorted by name ascending.

===== Examples

[#upload-tgz]
.Upload Contents
----
dataset.tgz
 ├─ foo.txt
 ├─ bar.xml
 ├─ fizz.json
 └─ buzz/
     └─ fazz.yml
----

.+<<input-files>>+
----
bar.xml buzz fizz.json foo.txt
----

===== `+<<input-files[n]>>+`

Array style access of the input file list allowing retrieval of a single file
name from the input file list.

====== Examples

These use <<#upload-tgz, this example input>>.

.+<<input-files[0]>>+
----
bar.xml
----

.+<<input-files[2]>>+
----
fizz.json
----

==== `+<<time>>+`

The current time formatted as `HH:MM:SS`.

.Example
----
03:47:58
----

==== `+<<timestamp>>+`

The current unix timestamp in seconds.

.Example
----
783647299
----
