= Exporter Script Server
// General Doc Settings
:toc: left
:source-highlighter: pygments
:icons: font
// Github specifics
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
Elizabeth Paige Harper <epharper@upenn.edu>
v1.0.0

// Custom Config
:repo-url: https://github.com/VEuPathDB/util-user-dataset-handler-server
:site-url: https://veupathdb.github.io/util-user-dataset-handler-server
:repo-file-base: {repo-url}/blob/master

// File paths
:file-base-readme: {repo-url}
:file-config-readme: {repo-file-base}/extras/readme/config-file.adoc
:file-command-readme: {repo-file-base}/extras/readme/commands.adoc
:file-api-readme: {repo-file-base}/api.raml
ifndef::env-github[]
include::extras/readme/include/site-config.adoc[]
endif::[]

{file-config-readme}[Configuration] | {file-command-readme}[Command Execution] | {file-api-readme}[API Docs]



Exposes configured exporter / validation scripts over HTTP.

== Usage

=== In Script Container

==== Standard Use

WARNING: TODO: Create demo script container repo and provide link here

==== Custom Use

To create a custom setup not based on the demo container, this server can be
configured by performing the following steps.

CAUTION: Currently, this server app only supports linux & mac environments.

. Download the latest release from the {repo-url}/releases/latest[releases page]
  and unpack the archive in your project directory.
. Run the command `./service gen-config` to generate a server configuration
  template file.  This file will be named `config.tpl.yml`.
. Edit the configuration file with your desired service name and command
  configurations.
+
NOTE: Check the {file-config-readme}[config file readme] for more
information about the configuration file.
. Once you have edited the configuration file, rename it and place it in the
  desired relative to the service binary.
. Validate the configuration by running the command
  `./service check-config --config=path/to/your/config.yml`.  This command will
  validate the configuration and report any errors.
+
.Bad Config Example
[source, bash-session]
----
$ ./service --config=config.yml check-config

----
