= Command Execution
// General Doc Settings
:toc: left
:source-highlighter: pygments
:icons: font
// Github specifics
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
Elizabeth Paige Harper <epharper@upenn.edu>
v1.0.0

// Custom Config
:repo-url: https://github.com/VEuPathDB/util-exporter-server
:site-url: https://veupathdb.github.io/util-exporter-server
:repo-file-base: {repo-url}/blob/master

// File paths
:file-base-readme: {repo-url}
:file-config-readme: {repo-file-base}/extras/readme/config-file.adoc
:file-command-readme: {repo-file-base}/extras/readme/commands.adoc
:file-api-readme: {repo-file-base}/openapi.yml
ifndef::env-github[]
include::include/site-config.adoc[]
endif::[]

{file-base-readme}[Index] | {file-config-readme}[Configuration] | {file-api-readme}[API Docs]

== Execution

=== Sequence

Scripts will be executed in the order in which they were configured.

If a script returns a non-0 exit code, and no output file was generated, it will
be interpreted as an unexpected error, no further scripts will be executed, and
the service will return a 500. For information about how a script should return
non-500 errors, see <<Script Expectations>>.

=== Environment

The scripts will be run with the same environment variables as the server
itself.

The script environment will be isolated from the server's environment.  If a
script needs to pass information along to a following script via the
environment, it may use the <<Environment Modification>> feature via the
<<Output File>>.

== Script Expectations

=== Exit Codes

Each script is expected to return an output file in all predictable
circumstances.  In the event of a predictable error, such as a badly formatted
input file, a script may return a non-0 exit code after writing an output file
describing the error.

If a non-0 exit code is returned, the server will check for an output json file.
If that file exists, the server will determine the status code and error
response based on the contents of that file.  If the file does not exist, the
server will assume 500.

=== Output File

The output of each script run should be a file in the workspace directory named
`process-results.json`.

.Output File JSON Schema
[source, json]
----
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "status": {
          "description": "Process completion status.",
          "type": "string",
          "enum": [
            "error",
            "user-error"
          ]
        },
        "message": {
          "description": "Optional message describing ",
          "type": "string"
        }
      },
      "required": [
        "status",
        "message"
      ]
    }, {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "enum": [  "success" ]
        },
        "outputFiles": {
          "description": "List of generated files relative to the working directory",
          "type": "array",
          "items": {
            "type": "string"
          },
          "examples": [
            ["file1.txt", "file2.bw"]
          ]
        },
        "packFiles": {
          "description": "List of files that are considered 'complete' and should be packaged in the output archive",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "environment": {
          "type": "object",
          "additionalProperties": {
            "type": [ "string", "null" ]
          }
        }
      },
      "required": [
        "status",
        "outputFiles"
      ]
    }
  ]
}
----

==== Exit Status

The exit `status` describes the completion state for the process, this will
inform the server whether it is safe to proceed to the next command in the
config.

* If the `status` value equals `success`, the server will expect at least a list
of output files.  If the `outputFiles` property is not set, the server will end
execution and return a `500`.

* If the `status` value does not equal `success` the server will expect a message
describing the issue.  If the message is not present, the server will return
a `500` error.

The statuses will result in behavior according to the following:

`success`:: The server will either run the next script in the config, or package
  the aggregated list of `packFiles` entries and return the completed archive
  with a `200` status code.

`user-error`:: The server will end execution of the scripts and return a `400`
  error with the message provided in the `process-results.json` file.

`error`:: The server will end execution of the scripts and return a `500` error
  with the message provided in the `process-results.json` file.

==== Generated Files

The generated files list (`outputFiles`) should contain all files created or
modified by the previous script.  The files in this list will be available to
the next script through the `\<<output-files>>` config template variable in the
order they appear in this list.

==== Completed Files

The completed files list `packFiles` are files that are considered "done" and
will be packaged in the output archive under the `datafiles` directory.

These files may be reported by any script and the server will aggregate the
lists from all the commands and archive all the files reported in `packFiles`
by all commands.

==== Environment Modification

If a script wants to set one or more environment variables to be read by the
following scripts, it may provide a map of variable to value using the
`environment` object.

.Setting an environment variable
[source, json]
----
{
  "environment": {
    "SOME_VAR": "some value"
  }
}
----

These values will be added to the environment for all following scripts.

Additionally, environment variables can be removed from the environment of
following scripts by setting the value of that variable to null in the
`environment` object.

.Deleting an environment variable
[source, json]
----
{
  "environment": {
    "SOME_VAR": null
  }
}
----

== Server Expectations

=== Building a valid archive

The server will handle:

. Generating the `dataset.json` file
. Generating the `meta.json` file
. Packaging the reported `packFiles` in the `datafiles` directory
. Packing the completed dataset files in a tar archive suitable for pushing to
  iRODS.
