= Command Execution
// General Doc Settings
:toc: left
:source-highlighter: pygments
:icons: font
// Github specifics
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
Elizabeth Paige Harper <epharper@upenn.edu>
v1.0.0

// Custom Config
:repo-url: https://github.com/VEuPathDB/util-exporter-server
:site-url: https://veupathdb.github.io/util-exporter-server
:repo-file-base: {repo-url}/blob/master

// File paths
:file-base-readme: {repo-url}
:file-config-readme: {repo-file-base}/extras/readme/config-file.adoc
:file-command-readme: {repo-file-base}/extras/readme/commands.adoc
:file-api-readme: {repo-file-base}/openapi.yml
ifndef::env-github[]
include::include/site-config.adoc[]
endif::[]

{file-base-readme}[Index] | {file-config-readme}[Configuration] | {file-api-readme}[API Docs]

== Execution

=== Sequence

Scripts will be executed in the order in which they were configured.

If a script returns a non-0 exit code, and no output file was generated, it will
be interpreted as an unexpected error, no further scripts will be executed, and
the service will return a 500. For information about how a script should return
non-500 errors, see <<Script Expectations>>.

=== Environment

The scripts will be run with the same environment variables as the server
itself.

The script environment will be isolated from the server's environment.  If a
script needs to pass information along to a following script via the
environment, it may use the <<Environment Modification>> feature via the
<<Output File>>.

== Script Expectations

=== Exit Codes

Each script is expected to return an output file in all predictable
circumstances.  In the event of a predictable error, such as a badly formatted
input file, a script may return a non-0 exit code after writing an output file
describing the error.

If a non-0 exit code is returned, the server will check for an output json file.
If that file exists, the server will determine the status code and error
response based on the contents of that file.  If the file does not exist, the
server will assume 500.

=== Output File

The output of each script run should be a file in the workspace directory named
`process-results.json`.

.Output File JSON Schema
[%collapse]
====
[source, json]
----
{}
----
====

==== Exit Status

==== Generated Files

==== Completed Files

==== Environment Modification