= Service Configuration
// General Doc Settings
:toc: left
:source-highlighter: pygments
:icons: font
// Github specifics
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
Elizabeth Paige Harper <epharper@upenn.edu>
v1.0.0

// Custom Config
:repo-url: https://github.com/VEuPathDB/util-exporter-server
:site-url: https://veupathdb.github.io/util-exporter-server
:repo-file-base: {repo-url}/blob/master

// File paths
:file-base-readme: {repo-url}
:file-config-readme: {repo-file-base}/extras/readme/config-file.adoc
:file-command-readme: {repo-file-base}/extras/readme/commands.adoc
:file-api-readme: {repo-file-base}/openapi.yml
ifndef::env-github[]
include::include/site-config.adoc[]
endif::[]

{file-base-readme}[Index] | {file-command-readme}[Command Execution] | {file-api-readme}[API Docs]


== Basics

The most basic service config will contain at least 2 things.

. A service name, used to differentiate this dataset handler service from others
  running the same service app.
. A command listing, where the dataset processing commands the service will
  execute are defined.

The template config file generated by the service will contain these elements.

.Generated Config Template
[source, yaml]
----
# Config Template
#
# Please edit the variables below and rename this file.
service-name: my service
commands:
  - command: my-command <1>
    args: <2>
      - '-v'
      - some string <3>
      - <<input-files>> <4>
----
<1> The path to or name of the command to execute.  This command must be
    reachable by the service at run time.
<2> A list of arguments that will be passed to the service.  Each individual
    argument/flag must be separated into separate list items.
<3> Multi-word arguments will be treated as a single arg at execution time.
    Behaving as if the command was called as `cmd "some string"`.
<4> Arguments may include <<Template Variables>>, denoted by double angle
    brackets `<<` `>>`.  These will be replaced at command execution time with
    values from the service.

== Command Execution

Configured commands will be executed in the order defined in the config file.
If any command returns a non-0 status, the server will interpret that as an

== Template Variables

The following variables, when encountered in a command config, will be replaced
with service provided data as defined below.

=== Time and Date

==== `\<<date>>`

The date the request started formatted in UTC time as `YYYY-MM-DD`.

Example: `1999-10-31`.

==== `\<<time>>`

The time the request started formatted in UTC time as `HH:MM:SS`.

Example: `16:05:48`.

==== `\<<date-time>>`

The date & time the request started in UTC time formatted according to ISO 8601.

Example `1999-10-31T16:05:48Z`

==== `\<<timestamp>>`

The Unix timestamp (in seconds) in UTC time.

Example: `941385948`.


=== Request Details

==== `\<<user-id>>`

The WDK user ID of the user that initiated the request.

==== `\<<request-id>>`

The unique identifier assigned to this request.  Format will be UUID v4.

Example: `b79822e9-0161-4de3-93f5-dfdb79c17f5d`

=== Workspace / File Info

==== `\<<input-files>>`

The list of uploaded files sorted by name in ascending order.  When used in this
form, the list will be injected as a space separated string.

Additionally, this template variable can be accessed as a zero-indexed array to
get the name of an individual input file.  Example: `\<<input-files[0]>>`.

NOTE: The expected number of files will depend on the script itself and its
expectations.

==== `\<<cwd>>`

The path to the working directory for the request.

==== `\<<output-files>>`

The list of files created by the previous command in the order reported by the
command.  When used in this form, the list will be injected as a space separated
string.

Additionally, this template variable can be accessed as either a one-dimensional
or two-dimensional array with the following behavior:

===== `\<<output-files[x]>>`

Use as a one-dimensional array will allow access to the files output by command
`x` in the list of defined commands.  `x` is the 0 based integer index of the
defined command.  Used in this form, the injected string will be a space
separated file list.

===== `\<<output-files[x][y]>>`

Use as a two-dimensional array allows access to specific file names from
specific previous commands.  Similar to `\<<input-files[x]>>`.  Here `x` is the
zero-based index of the command in the defined command list and `y` is the
zero-based index of the file name in the list of output files.
